#!/bin/bash

# Launch a jupyter notebook server on a specified port without opening a browser.
# This is useful for running an ipython notebook on a remote server.
# To use, copy this file onto the remote machine, make sure it's directory 
# is in the path (I like /usr/local/bin, but that may not be writeable on a cluster), 
# and then run and specify a port (defaults to 6969):
# launch-jupyter-notebook-server -p 7001

HELP_MSG="
\nlaunch-jupyter-notebook-server\n------------------------------\n
\nLaunch a jupyter notebook server.
You would run this on the host machine.\n\nlaunch-juptyer-notebook-server takes one optional argument:\n\n     
-p The port to launch the server on\n
Ex.: launch-jupyter-notebook-server -p 6969
"

HELP=''
PORT='6969'
while getopts 'p:' flag; do
    case "${flag}" in
        p) PORT="${OPTARG}" ;;
        *) error "Unexpected option ${flag}" ; echo -e ${HELP_MSG}; exit;
    esac
done


jupyter-notebook --no-browser --port=${PORT}
