#!/bin/bash

# Connect to a remote ipython notebook server (previously launched, e.g.,
# with launch-juptyer-notebook-server. Pass flags -h <remote_host>, -r <remote_port>,
# and -p <local_port>. You must ensure the remote port is the same as the one 
# where the notebook was launched on the remote server.
# Example:
# launch-remote-jupyter-notebook -h foo@bar.baz -r 6969 -p 8888

REMOTE_HOST=''
REMOTE_PORT='6969'
LOCAL_PORT='8888'

while getopts 'h:r:p:' flag; do
    case "${flag}" in
        h) REMOTE_HOST="${OPTARG}" ;;
        r) REMOTE_PORT="${OPTARG}" ;;
        p) LOCAL_PORT="${OPTARG}" ;;
        *) error "Unexpected option ${flag}" ; echo -e ${HELP_MSG}; exit;
    esac
done


echo "Connecting to ${REMOTE_HOST}"
ssh -N -f -L localhost:${LOCAL_PORT}:localhost:${REMOTE_PORT} ${REMOTE_HOST}
open -a /Applications/Google\ Chrome.app/ http://localhost:${LOCAL_PORT}
